# SlackJanitor configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn
      - save_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
      - run:
          name: "Linting via prettier"
          command: yarn lint:format
      - run:
          name: "Get the version"
          command: |
            mkdir -p workspace
            node -p "require('./package.json').version" > workspace/version.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - version.txt

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test --collectCoverage=true
      - store_artifacts:
          path: coverage

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./workspace/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./workspace/

workflows:
  version: 2
  install_lint_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
          filters:
            branches:
              ignore:
                - /none
      - publish-github-release:
          requires:
            - install
            - lint
            - test
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/
