defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn
      - save_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test --collectCoverage=true
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /none
