name: Tag

on:
  push:
    branches:
      - '*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: node -p "require('./package.json').version" > version.txt
    # - uses: actions/github-script@0.2.0
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     script: |
    #       console.log(process.env);
    #       return "1.2.0";
    # - name: Create a Release
    #   uses: frankjuniorr/github-create-release-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     VERSION: ${{ steps.output.result }}