name: Tag

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: butlerlogic/action-autotag@1.0.2
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"