name: Tag

on:
  push:
    branches:
      - '*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: export RELEASE_VERSION=$(node -p "require('./package.json').version")
    - name: Create a Release
      uses: frankjuniorr/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ RELEASE_VERSION }}